font_family JetBrains Mono
font_size 8
background #1D281D
foreground #d6e2d3
cursor #9bc79a
cursor_text_color #1D281D
selection_background #355235
selection_foreground #e6efe2
color0  #1D281D
color8  #2a3a2a
color1  #3a4d3a
color9  #4e6650
color2  #7fa37a
color10 #9bc79a
color3  #5f6f5f
color11 #7f9a7f
color4  #4f6a5a
color12 #6f8f7a
color5  #5a6a5a
color13 #7a8f7a
color6  #6a8f7a
color14 #8fb3a0
color7  #d6e2d3
color15 #eef7ea
confirm_os_window_close 0
